import { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service | 1nguoi',
  description: 'Terms of Service for using 1nguoi platform',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
      <div className="container mx-auto px-4 py-16 max-w-4xl">
        <Link
          href="/"
          className="inline-flex items-center text-slate-400 hover:text-white mb-8 transition-colors"
        >
          <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
          Back to Home
        </Link>

        <h1 className="text-4xl font-bold text-white mb-8">Terms of Service</h1>

        <div className="prose prose-invert prose-slate max-w-none">
          <p className="text-slate-300 text-lg mb-6">
            Last updated: January 2026
          </p>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
            <p className="text-slate-300">
              By accessing and using 1nguoi (&quot;the Service&quot;), you accept and agree to be bound by these Terms of Service.
              If you do not agree to these terms, please do not use our Service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">2. Description of Service</h2>
            <p className="text-slate-300">
              1nguoi provides AI-powered tools for brainstorming, collaboration, and content generation.
              Our services include but are not limited to:
            </p>
            <ul className="list-disc list-inside text-slate-300 mt-4 space-y-2">
              <li>AI Chat and Discussion Rooms (Combat)</li>
              <li>Project Management Tools</li>
              <li>Idea Generation and Brainstorming</li>
              <li>Code Generation (VibeCode)</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">3. User Accounts</h2>
            <p className="text-slate-300">
              To access certain features, you must create an account. You are responsible for:
            </p>
            <ul className="list-disc list-inside text-slate-300 mt-4 space-y-2">
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>All activities that occur under your account</li>
              <li>Notifying us immediately of any unauthorized use</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">4. Acceptable Use</h2>
            <p className="text-slate-300">
              You agree not to use the Service to:
            </p>
            <ul className="list-disc list-inside text-slate-300 mt-4 space-y-2">
              <li>Generate harmful, illegal, or offensive content</li>
              <li>Infringe on intellectual property rights</li>
              <li>Distribute malware or conduct cyber attacks</li>
              <li>Harass, abuse, or harm others</li>
              <li>Violate any applicable laws or regulations</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">5. AI-Generated Content</h2>
            <p className="text-slate-300">
              Content generated by our AI tools is provided as-is. While we strive for accuracy,
              AI outputs may contain errors or inaccuracies. You are responsible for reviewing
              and verifying any AI-generated content before use.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">6. Intellectual Property</h2>
            <p className="text-slate-300">
              You retain ownership of content you create using our Service. By using the Service,
              you grant us a license to process and store your content as necessary to provide the Service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">7. Payment and Billing</h2>
            <p className="text-slate-300">
              Some features may require payment. By subscribing to paid services, you agree to
              pay all applicable fees. Refunds are handled according to our refund policy.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">8. Limitation of Liability</h2>
            <p className="text-slate-300">
              The Service is provided &quot;as is&quot; without warranties of any kind. We shall not be liable
              for any indirect, incidental, special, or consequential damages arising from your use
              of the Service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">9. Changes to Terms</h2>
            <p className="text-slate-300">
              We may modify these terms at any time. Continued use of the Service after changes
              constitutes acceptance of the modified terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">10. Contact</h2>
            <p className="text-slate-300">
              For questions about these Terms, please contact us at{' '}
              <a href="mailto:support@1nguoi.com" className="text-purple-400 hover:text-purple-300">
                support@1nguoi.com
              </a>
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-slate-700">
          <Link href="/privacy" className="text-purple-400 hover:text-purple-300">
            View Privacy Policy →
          </Link>
        </div>
      </div>
    </div>
  )
}
